version: '3.8'

services:
  api:
    image: node:20-alpine
    container_name: task-api
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tasks_db
      - JWT_SECRET=supersecret123
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: task-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
