/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id?: number;
            username?: string;
            email?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Task: {
            id?: number;
            title?: string;
            description?: string;
            /** @enum {string} */
            status?: "pending" | "in_progress" | "completed";
            user_id?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ValidationError: {
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
